# Generated by Django 5.2.9 on 2025-12-18 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.CharField(default='01KCR6N1EQX22EK7H9FZE95N48', editable=False, max_length=26, primary_key=True, serialize=False),
        ),
    ]
